import 'package:flutter/cupertino.dart';
import 'package:ledger_app/core/domain/enums/app_icon.dart';

extension AppIconX on AppIcon {
  IconData get iconData {
    switch (this) {
      case AppIcon.airplane:
        return CupertinoIcons.airplane;
      case AppIcon.bag:
        return CupertinoIcons.bag;
      case AppIcon.book:
        return CupertinoIcons.book;
      case AppIcon.bookmark:
        return CupertinoIcons.bookmark;
      case AppIcon.building:
        return CupertinoIcons.building_2_fill;
      case AppIcon.bus:
        return CupertinoIcons.bus;
      case AppIcon.camera:
        return CupertinoIcons.camera;
      case AppIcon.car:
        return CupertinoIcons.car_detailed;
      case AppIcon.cart:
        return CupertinoIcons.shopping_cart;
      case AppIcon.chartPie:
        return CupertinoIcons.chart_pie;
      case AppIcon.creditCard:
        return CupertinoIcons.creditcard;
      case AppIcon.desktop:
        return CupertinoIcons.desktopcomputer;
      case AppIcon.drop:
        return CupertinoIcons.drop;
      case AppIcon.film:
        return CupertinoIcons.film;
      case AppIcon.flame:
        return CupertinoIcons.flame;
      case AppIcon.folder:
        return CupertinoIcons.folder;
      case AppIcon.gameController:
        return CupertinoIcons.gamecontroller;
      case AppIcon.gift:
        return CupertinoIcons.gift;
      case AppIcon.globe:
        return CupertinoIcons.globe;
      case AppIcon.group:
        return CupertinoIcons.group;
      case AppIcon.hammer:
        return CupertinoIcons.hammer;
      case AppIcon.heart:
        return CupertinoIcons.heart;
      case AppIcon.house:
        return CupertinoIcons.house;
      case AppIcon.lightbulb:
        return CupertinoIcons.lightbulb;
      case AppIcon.map:
        return CupertinoIcons.map;
      case AppIcon.mic:
        return CupertinoIcons.mic;
      case AppIcon.money:
        return CupertinoIcons.money_dollar;
      case AppIcon.music:
        return CupertinoIcons.music_note;
      case AppIcon.paintbrush:
        return CupertinoIcons.paintbrush;
      case AppIcon.paperplane:
        return CupertinoIcons.paperplane;
      case AppIcon.paw:
        return CupertinoIcons.paw;
      case AppIcon.person:
        return CupertinoIcons.person;
      case AppIcon.phone:
        return CupertinoIcons.phone;
      case AppIcon.pin:
        return CupertinoIcons.pin;
      case AppIcon.scissors:
        return CupertinoIcons.scissors;
      case AppIcon.shield:
        return CupertinoIcons.shield;
      case AppIcon.smiley:
        return CupertinoIcons.smiley;
      case AppIcon.speaker:
        return CupertinoIcons.speaker_2;
      case AppIcon.sportscourt:
        return CupertinoIcons.sportscourt;
      case AppIcon.star:
        return CupertinoIcons.star;
      case AppIcon.stopwatch:
        return CupertinoIcons.stopwatch;
      case AppIcon.sun:
        return CupertinoIcons.sun_max;
      case AppIcon.tag:
        return CupertinoIcons.tag;
      case AppIcon.thermometer:
        return CupertinoIcons.thermometer;
      case AppIcon.ticket:
        return CupertinoIcons.ticket;
      case AppIcon.train:
        return CupertinoIcons.tram_fill;
      case AppIcon.tv:
        return CupertinoIcons.tv;
      case AppIcon.umbrella:
        return CupertinoIcons.umbrella;
      case AppIcon.wifi:
        return CupertinoIcons.wifi;
      case AppIcon.wrench:
        return CupertinoIcons.wrench;
      case AppIcon.question:
        return CupertinoIcons.question;
    }
  }
}
