import 'package:ledger_app/core/currencies/currency_format_info.dart';

const Map<String, CurrencyFormatInfo> currencies = {
  'USD': CurrencyFormatInfo(
    code: 'USD',
    name: 'United States Dollar',
    symbol: r'$',
    flag: 'USD',
    decimalDigits: 2,
    number: 840,
    namePlural: 'US dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'EUR': CurrencyFormatInfo(
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    flag: 'EUR',
    decimalDigits: 2,
    number: 978,
    namePlural: 'Euros',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'JPY': CurrencyFormatInfo(
    code: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    flag: 'JPY',
    decimalDigits: 0,
    number: 392,
    namePlural: 'Japanese yen',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'GBP': CurrencyFormatInfo(
    code: 'GBP',
    name: 'British Pound',
    symbol: '£',
    flag: 'GBP',
    decimalDigits: 2,
    number: 826,
    namePlural: 'British pounds sterling',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'AUD': CurrencyFormatInfo(
    code: 'AUD',
    name: 'Australian Dollar',
    symbol: r'$',
    flag: 'AUD',
    decimalDigits: 2,
    number: 36,
    namePlural: 'Australian dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'CAD': CurrencyFormatInfo(
    code: 'CAD',
    name: 'Canadian Dollar',
    symbol: r'$',
    flag: 'CAD',
    decimalDigits: 2,
    number: 124,
    namePlural: 'Canadian dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'CHF': CurrencyFormatInfo(
    code: 'CHF',
    name: 'Switzerland Franc',
    symbol: 'CHF',
    flag: 'CHF',
    decimalDigits: 2,
    number: 756,
    namePlural: 'Swiss francs',
    thousandsSeparator: "'",
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'CNY': CurrencyFormatInfo(
    code: 'CNY',
    name: 'China Yuan Renminbi',
    symbol: '¥',
    flag: 'CNY',
    decimalDigits: 2,
    number: 156,
    namePlural: 'Chinese yuan',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'HKD': CurrencyFormatInfo(
    code: 'HKD',
    name: 'Hong Kong Dollar',
    symbol: r'$',
    flag: 'HKD',
    decimalDigits: 2,
    number: 344,
    namePlural: 'Hong Kong dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'NZD': CurrencyFormatInfo(
    code: 'NZD',
    name: 'New Zealand Dollar',
    symbol: r'$',
    flag: 'NZD',
    decimalDigits: 2,
    number: 554,
    namePlural: 'New Zealand dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'SEK': CurrencyFormatInfo(
    code: 'SEK',
    name: 'Sweden Krona',
    symbol: 'kr',
    flag: 'SEK',
    decimalDigits: 2,
    number: 752,
    namePlural: 'Swedish kronor',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'KRW': CurrencyFormatInfo(
    code: 'KRW',
    name: 'South Korea Won',
    symbol: '₩',
    flag: 'KRW',
    decimalDigits: 0,
    number: 410,
    namePlural: 'South Korean won',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'SGD': CurrencyFormatInfo(
    code: 'SGD',
    name: 'Singapore Dollar',
    symbol: r'$',
    flag: 'SGD',
    decimalDigits: 2,
    number: 702,
    namePlural: 'Singapore dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'NOK': CurrencyFormatInfo(
    code: 'NOK',
    name: 'Norway Krone',
    symbol: 'kr',
    flag: 'NOK',
    decimalDigits: 2,
    number: 578,
    namePlural: 'Norwegian kroner',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'MXN': CurrencyFormatInfo(
    code: 'MXN',
    name: 'Mexico Peso',
    symbol: r'$',
    flag: 'MXN',
    decimalDigits: 2,
    number: 484,
    namePlural: 'Mexican pesos',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'INR': CurrencyFormatInfo(
    code: 'INR',
    name: 'Indian Rupee',
    symbol: '₹',
    flag: 'INR',
    decimalDigits: 2,
    number: 356,
    namePlural: 'Indian rupees',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'RUB': CurrencyFormatInfo(
    code: 'RUB',
    name: 'Russia Ruble',
    symbol: '₽',
    flag: 'RUB',
    decimalDigits: 2,
    number: 643,
    namePlural: 'Russian rubles',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'ZAR': CurrencyFormatInfo(
    code: 'ZAR',
    name: 'South Africa Rand',
    symbol: 'R',
    flag: 'ZAR',
    decimalDigits: 2,
    number: 710,
    namePlural: 'South African rand',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'TRY': CurrencyFormatInfo(
    code: 'TRY',
    name: 'Turkish Lira',
    symbol: '₺',
    flag: 'TRY',
    decimalDigits: 2,
    number: 949,
    namePlural: 'Turkish Lira',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'BRL': CurrencyFormatInfo(
    code: 'BRL',
    name: 'Brazilian Real',
    symbol: r'R$',
    flag: 'BRL',
    decimalDigits: 2,
    number: 986,
    namePlural: 'Brazilian Reais',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'TWD': CurrencyFormatInfo(
    code: 'TWD',
    name: 'Taiwan New Dollar',
    symbol: r'NT$',
    flag: 'TWD',
    decimalDigits: 2,
    number: 901,
    namePlural: 'New Taiwan dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'DKK': CurrencyFormatInfo(
    code: 'DKK',
    name: 'Denmark Krone',
    symbol: 'kr',
    flag: 'DKK',
    decimalDigits: 2,
    number: 208,
    namePlural: 'Danish kroner',
    thousandsSeparator: '',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'PLN': CurrencyFormatInfo(
    code: 'PLN',
    name: 'Poland Zloty',
    symbol: 'zł',
    flag: 'PLN',
    decimalDigits: 2,
    number: 985,
    namePlural: 'Polish zlotys',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'THB': CurrencyFormatInfo(
    code: 'THB',
    name: 'Thailand Baht',
    symbol: '฿',
    flag: 'THB',
    decimalDigits: 2,
    number: 764,
    namePlural: 'Thai baht',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'IDR': CurrencyFormatInfo(
    code: 'IDR',
    name: 'Indonesia Rupiah',
    symbol: 'Rp',
    flag: 'IDR',
    decimalDigits: 0,
    number: 360,
    namePlural: 'Indonesian rupiahs',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'HUF': CurrencyFormatInfo(
    code: 'HUF',
    name: 'Hungary Forint',
    symbol: 'Ft',
    flag: 'HUF',
    decimalDigits: 0,
    number: 348,
    namePlural: 'Hungarian forints',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'CZK': CurrencyFormatInfo(
    code: 'CZK',
    name: 'Czech Koruna',
    symbol: 'Kč',
    flag: 'CZK',
    decimalDigits: 2,
    number: 203,
    namePlural: 'Czech Republic korunas',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'ILS': CurrencyFormatInfo(
    code: 'ILS',
    name: 'Israel Shekel',
    symbol: '₪',
    flag: 'ILS',
    decimalDigits: 2,
    number: 376,
    namePlural: 'Israeli new sheqels',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'CLP': CurrencyFormatInfo(
    code: 'CLP',
    name: 'Chile Peso',
    symbol: r'$',
    flag: 'CLP',
    decimalDigits: 0,
    number: 152,
    namePlural: 'Chilean pesos',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'PHP': CurrencyFormatInfo(
    code: 'PHP',
    name: 'Philippines Peso',
    symbol: '₱',
    flag: 'PHP',
    decimalDigits: 2,
    number: 608,
    namePlural: 'Philippine pesos',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'AED': CurrencyFormatInfo(
    code: 'AED',
    name: 'Emirati Dirham',
    symbol: 'د.إ',
    flag: 'AED',
    decimalDigits: 2,
    number: 784,
    namePlural: 'UAE dirhams',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'COP': CurrencyFormatInfo(
    code: 'COP',
    name: 'Colombia Peso',
    symbol: r'$',
    flag: 'COP',
    decimalDigits: 0,
    number: 170,
    namePlural: 'Colombian pesos',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'SAR': CurrencyFormatInfo(
    code: 'SAR',
    name: 'Saudi Arabia Riyal',
    symbol: '﷼',
    flag: 'SAR',
    decimalDigits: 2,
    number: 682,
    namePlural: 'Saudi riyals',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'MYR': CurrencyFormatInfo(
    code: 'MYR',
    name: 'Malaysia Ringgit',
    symbol: 'RM',
    flag: 'MYR',
    decimalDigits: 2,
    number: 458,
    namePlural: 'Malaysian ringgits',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'RON': CurrencyFormatInfo(
    code: 'RON',
    name: 'Romania Leu',
    symbol: 'L',
    flag: 'RON',
    decimalDigits: 2,
    number: 946,
    namePlural: 'Romanian lei',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'AFN': CurrencyFormatInfo(
    code: 'AFN',
    name: 'Afghanistan Afghani',
    symbol: '؋',
    flag: 'AFN',
    decimalDigits: 0,
    number: 971,
    namePlural: 'Afghan Afghanis',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'ALL': CurrencyFormatInfo(
    code: 'ALL',
    name: 'Albanian Lek',
    symbol: 'Lek',
    flag: 'ALB',
    decimalDigits: 0,
    number: 8,
    namePlural: 'Albanian lekë',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: false,
  ),
  'DZD': CurrencyFormatInfo(
    code: 'DZD',
    name: 'Algerian dinar',
    symbol: 'دج',
    flag: 'DZ',
    decimalDigits: 2,
    number: 12,
    namePlural: 'Algerian dinars',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: false,
  ),
  'ARS': CurrencyFormatInfo(
    code: 'ARS',
    name: 'Argentine Peso',
    symbol: r'$',
    flag: 'ARS',
    decimalDigits: 2,
    number: 32,
    namePlural: 'Argentine pesos',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'AMD': CurrencyFormatInfo(
    code: 'AMD',
    name: 'Armenian Dram',
    symbol: '֏',
    flag: 'AM',
    decimalDigits: 0,
    number: 51,
    namePlural: 'Armenian drams',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'AZN': CurrencyFormatInfo(
    code: 'AZN',
    name: 'Azerbaijani Manat',
    symbol: '₼',
    flag: 'AZE',
    decimalDigits: 2,
    number: 100,
    namePlural: 'Azerbaijani manats',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'BHD': CurrencyFormatInfo(
    code: 'BHD',
    name: 'Bahraini Dinar',
    symbol: 'BD',
    flag: 'BHD',
    decimalDigits: 3,
    number: 48,
    namePlural: 'Bahraini dinars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'BDT': CurrencyFormatInfo(
    code: 'BDT',
    name: 'Bangladeshi Taka',
    symbol: '৳',
    flag: 'BDT',
    decimalDigits: 2,
    number: 50,
    namePlural: 'Bangladeshi takas',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'BBD': CurrencyFormatInfo(
    code: 'BBD',
    name: 'Barbados Dollar',
    symbol: r'$',
    flag: 'BBD',
    decimalDigits: 2,
    number: 52,
    namePlural: 'Zimbabwean dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'BYN': CurrencyFormatInfo(
    code: 'BYN',
    name: 'Belarussian Ruble',
    symbol: 'Br',
    flag: 'BY',
    decimalDigits: 2,
    number: 933,
    namePlural: 'Belarusian rubles',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'BZD': CurrencyFormatInfo(
    code: 'BZD',
    name: 'Belize Dollar',
    symbol: r'BZ$',
    flag: 'BZD',
    decimalDigits: 2,
    number: 84,
    namePlural: 'Belize dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'BMD': CurrencyFormatInfo(
    code: 'BMD',
    name: 'Bermuda Dollar',
    symbol: r'$',
    flag: 'BMD',
    decimalDigits: 2,
    number: 60,
    namePlural: 'Bermuda dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'BTN': CurrencyFormatInfo(
    code: 'BTN',
    name: 'Bhutanese Ngultrum',
    symbol: 'Nu.',
    flag: 'BTN',
    decimalDigits: 2,
    number: 64,
    namePlural: 'Bhutanese ngultrums',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'BOB': CurrencyFormatInfo(
    code: 'BOB',
    name: 'Bolivia Bolíviano',
    symbol: r'$b',
    flag: 'BOB',
    decimalDigits: 2,
    number: 68,
    namePlural: 'Bolivian bolivianos',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'BAM': CurrencyFormatInfo(
    code: 'BAM',
    name: 'Bosnia and Herzegovina convertible mark',
    symbol: 'KM',
    flag: 'BA',
    decimalDigits: 2,
    number: 977,
    namePlural: 'Bosnia and Herzegovina convertible marks',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'BWP': CurrencyFormatInfo(
    code: 'BWP',
    name: 'Botswanan Pula',
    symbol: 'P',
    flag: 'BW',
    decimalDigits: 2,
    number: 72,
    namePlural: 'Botswanan pulas',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'BND': CurrencyFormatInfo(
    code: 'BND',
    name: 'Brunei Darussalam Dollar',
    symbol: r'$',
    flag: 'BND',
    decimalDigits: 2,
    number: 96,
    namePlural: 'Brunei dollars',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'BGN': CurrencyFormatInfo(
    code: 'BGN',
    name: 'Bulgarian Lev',
    symbol: 'лв',
    flag: 'BGN',
    decimalDigits: 2,
    number: 975,
    namePlural: 'Bulgarian leva',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'BIF': CurrencyFormatInfo(
    code: 'BIF',
    name: 'Burundian Franc',
    symbol: 'FBu',
    flag: 'BI',
    decimalDigits: 2,
    number: 108,
    namePlural: 'Burundian Franc',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'KHR': CurrencyFormatInfo(
    code: 'KHR',
    name: 'Cambodian riel',
    symbol: '៛',
    flag: 'KHM',
    decimalDigits: 2,
    number: 116,
    namePlural: 'Cambodian riels',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: false,
  ),
  'KYD': CurrencyFormatInfo(
    code: 'KYD',
    name: 'Cayman Islands Dollar',
    symbol: r'$',
    flag: 'KYD',
    decimalDigits: 2,
    number: 136,
    namePlural: 'Cayman islands dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'XAF': CurrencyFormatInfo(
    code: 'XAF',
    name: 'Central African CFA franc',
    symbol: 'FCFA',
    decimalDigits: 2,
    number: 950,
    namePlural: 'Central African CFA francs',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'XOF': CurrencyFormatInfo(
    code: 'XOF',
    name: 'UEMOA CFA franc',
    symbol: 'FCFA',
    flag: 'xof.png',
    decimalDigits: 2,
    number: 960,
    namePlural: 'UEMOA CFA francs',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'CDF': CurrencyFormatInfo(
    code: 'CDF',
    name: 'Congolese franc',
    symbol: 'FC',
    flag: 'CD',
    decimalDigits: 2,
    number: 976,
    namePlural: 'Congolese francs',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'CRC': CurrencyFormatInfo(
    code: 'CRC',
    name: 'Costa Rica Colon',
    symbol: '₡',
    flag: 'CRC',
    decimalDigits: 0,
    number: 188,
    namePlural: 'Costa Rican colóns',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'DOP': CurrencyFormatInfo(
    code: 'DOP',
    name: 'Dominican Republic Peso',
    symbol: r'RD$',
    flag: 'DOP',
    decimalDigits: 2,
    number: 214,
    namePlural: 'Dominican pesos',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'EGP': CurrencyFormatInfo(
    code: 'EGP',
    name: 'Egypt Pound',
    symbol: '£',
    flag: 'EGP',
    decimalDigits: 2,
    number: 818,
    namePlural: 'Egyptian pounds',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'ETB': CurrencyFormatInfo(
    code: 'ETB',
    name: 'Ethiopian Birr',
    symbol: 'Br',
    flag: 'ETB',
    decimalDigits: 2,
    number: 230,
    namePlural: 'Ethiopian birrs',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'GMD': CurrencyFormatInfo(
    code: 'GMD',
    name: 'Gambian dalasi',
    symbol: 'D',
    flag: 'GMD',
    decimalDigits: 2,
    number: 270,
    namePlural: 'Gambian dalasis',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: false,
  ),
  'GEL': CurrencyFormatInfo(
    code: 'GEL',
    name: 'Georgian Lari',
    symbol: '₾',
    flag: 'GEL',
    decimalDigits: 2,
    number: 981,
    namePlural: 'Georgian laris',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'GHS': CurrencyFormatInfo(
    code: 'GHS',
    name: 'Ghana Cedi',
    symbol: '₵',
    flag: 'GHS',
    decimalDigits: 2,
    number: 936,
    namePlural: 'Ghanaian cedis',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'GTQ': CurrencyFormatInfo(
    code: 'GTQ',
    name: 'Guatemalan quetzal',
    symbol: 'Q',
    flag: 'GT',
    decimalDigits: 2,
    number: 320,
    namePlural: 'Guatemalan quetzales',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'GYD': CurrencyFormatInfo(
    code: 'GYD',
    name: 'Guyana Dollar',
    symbol: r'$',
    flag: 'GYD',
    decimalDigits: 2,
    number: 328,
    namePlural: 'Guyana dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'HTG': CurrencyFormatInfo(
    code: 'HTG',
    name: 'Haitian gourde',
    symbol: 'G',
    flag: 'HTI',
    decimalDigits: 2,
    number: 332,
    namePlural: 'Haitian gourdes',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'ISK': CurrencyFormatInfo(
    code: 'ISK',
    name: 'Iceland Krona',
    symbol: 'kr',
    flag: 'ISK',
    decimalDigits: 0,
    number: 352,
    namePlural: 'Icelandic krónur',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'JMD': CurrencyFormatInfo(
    code: 'JMD',
    name: 'Jamaica Dollar',
    symbol: r'J$',
    flag: 'JMD',
    decimalDigits: 2,
    number: 388,
    namePlural: 'Jamaican dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'JOD': CurrencyFormatInfo(
    code: 'JOD',
    name: 'Jordanian dinar',
    symbol: 'د.أ',
    flag: 'JO',
    decimalDigits: 3,
    number: 400,
    namePlural: 'Jordanian dinars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: false,
  ),
  'KZT': CurrencyFormatInfo(
    code: 'KZT',
    name: 'Kazakhstan Tenge',
    symbol: '〒',
    flag: 'KZT',
    decimalDigits: 2,
    number: 398,
    namePlural: 'Kazakhstani tenges',
    thousandsSeparator: ' ',
    decimalSeparator: '-',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'KES': CurrencyFormatInfo(
    code: 'KES',
    name: 'Kenyan Shilling',
    symbol: 'KSh',
    flag: 'KES',
    decimalDigits: 2,
    number: 404,
    namePlural: 'Kenyan shillings',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'KWD': CurrencyFormatInfo(
    code: 'KWD',
    name: 'Kuwaiti Dinar',
    symbol: 'د.ك',
    flag: 'KWD',
    decimalDigits: 3,
    number: 414,
    namePlural: 'Kuwaiti dinars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'KGS': CurrencyFormatInfo(
    code: 'KGS',
    name: 'Kyrgyzstani som',
    symbol: 'с',
    flag: 'KG',
    decimalDigits: 2,
    number: 417,
    namePlural: 'Kyrgyzstani som',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'LAK': CurrencyFormatInfo(
    code: 'LAK',
    name: 'Laos Kip',
    symbol: '₭',
    flag: 'LAK',
    decimalDigits: 2,
    number: 418,
    namePlural: 'Laos Kip',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: false,
  ),
  'LRD': CurrencyFormatInfo(
    code: 'LRD',
    name: 'Liberia Dollar',
    symbol: r'$',
    flag: 'LRD',
    decimalDigits: 2,
    number: 430,
    namePlural: 'Liberia dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'MKD': CurrencyFormatInfo(
    code: 'MKD',
    name: 'Macedonia Denar',
    symbol: 'ден',
    flag: 'MKD',
    decimalDigits: 2,
    number: 807,
    namePlural: 'Macedonian denari',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'MWK': CurrencyFormatInfo(
    code: 'MWK',
    name: 'Malawian Kwacha',
    symbol: 'MK',
    flag: 'MWK',
    decimalDigits: 2,
    number: 454,
    namePlural: 'Malawian kwachas',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'MUR': CurrencyFormatInfo(
    code: 'MUR',
    name: 'Mauritius Rupee',
    symbol: '₨',
    flag: 'MUR',
    decimalDigits: 0,
    number: 480,
    namePlural: 'Mauritian rupees',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'MDL': CurrencyFormatInfo(
    code: 'MDL',
    name: 'Moldovan Leu',
    symbol: 'L',
    flag: 'MDL',
    decimalDigits: 2,
    number: 498,
    namePlural: 'Moldovan lei',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'MNT': CurrencyFormatInfo(
    code: 'MNT',
    name: 'Mongolia Tughrik',
    symbol: '₮',
    flag: 'MNT',
    decimalDigits: 2,
    number: 496,
    namePlural: 'Mongolia tugriks',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'MAD': CurrencyFormatInfo(
    code: 'MAD',
    name: 'Moroccan Dirham',
    symbol: 'MAD',
    flag: 'MAD',
    decimalDigits: 2,
    number: 504,
    namePlural: 'Moroccan dirhams',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'MZN': CurrencyFormatInfo(
    code: 'MZN',
    name: 'Mozambique Metical',
    symbol: 'MT',
    flag: 'MZN',
    decimalDigits: 2,
    number: 943,
    namePlural: 'Mozambican meticals',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'MMK': CurrencyFormatInfo(
    code: 'MMK',
    name: 'Myanmar Kyat',
    symbol: 'Ks',
    flag: 'MM',
    decimalDigits: 2,
    number: 104,
    namePlural: 'Myanmar Kyats',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'NAD': CurrencyFormatInfo(
    code: 'NAD',
    name: 'Namibia Dollar',
    symbol: r'$',
    flag: 'NAD',
    decimalDigits: 2,
    number: 516,
    namePlural: 'Namibian dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'NPR': CurrencyFormatInfo(
    code: 'NPR',
    name: 'Nepal Rupee',
    symbol: '₨',
    flag: 'NPR',
    decimalDigits: 2,
    number: 524,
    namePlural: 'Nepalese rupees',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'NIO': CurrencyFormatInfo(
    code: 'NIO',
    name: 'Nicaragua Cordoba',
    symbol: r'C$',
    flag: 'NIO',
    decimalDigits: 2,
    number: 558,
    namePlural: 'Nicaraguan córdobas',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'NGN': CurrencyFormatInfo(
    code: 'NGN',
    name: 'Nigeria Naira',
    symbol: '₦',
    flag: 'NGN',
    decimalDigits: 2,
    number: 566,
    namePlural: 'Nigerian nairas',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'OMR': CurrencyFormatInfo(
    code: 'OMR',
    name: 'Oman Rial',
    symbol: '﷼',
    flag: 'OMR',
    decimalDigits: 3,
    number: 512,
    namePlural: 'Omani rials',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'PKR': CurrencyFormatInfo(
    code: 'PKR',
    name: 'Pakistan Rupee',
    symbol: '₨',
    flag: 'PKR',
    decimalDigits: 0,
    number: 586,
    namePlural: 'Pakistani rupees',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'PGK': CurrencyFormatInfo(
    code: 'PGK',
    name: 'Papua New Guinean Kina',
    symbol: 'K',
    flag: 'PGK',
    decimalDigits: 2,
    number: 598,
    namePlural: 'Papua New Guinean Kina',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'PYG': CurrencyFormatInfo(
    code: 'PYG',
    name: 'Paraguay Guarani',
    symbol: '₲',
    flag: 'PYG',
    decimalDigits: 0,
    number: 600,
    namePlural: 'Paraguayan guaranis',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'PEN': CurrencyFormatInfo(
    code: 'PEN',
    name: 'Peru Sol',
    symbol: 'S/.',
    flag: 'PEN',
    decimalDigits: 2,
    number: 604,
    namePlural: 'Peruvian nuevos soles',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'QAR': CurrencyFormatInfo(
    code: 'QAR',
    name: 'Qatar Riyal',
    symbol: '﷼',
    flag: 'QAR',
    decimalDigits: 2,
    number: 634,
    namePlural: 'Qatari rials',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'RWF': CurrencyFormatInfo(
    code: 'RWF',
    name: 'Rwandan franc',
    symbol: 'FRw',
    flag: 'RWA',
    decimalDigits: 0,
    number: 646,
    namePlural: 'Rwandan francs',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'RSD': CurrencyFormatInfo(
    code: 'RSD',
    name: 'Serbia Dinar',
    symbol: 'Дин.',
    flag: 'RSD',
    decimalDigits: 0,
    number: 941,
    namePlural: 'Serbian dinars',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'SCR': CurrencyFormatInfo(
    code: 'SCR',
    name: 'Seychellois rupee',
    symbol: '₨',
    flag: 'SC',
    decimalDigits: 2,
    number: 690,
    namePlural: 'Seychelles rupee',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'SOS': CurrencyFormatInfo(
    code: 'SOS',
    name: 'Somalia Shilling',
    symbol: 'S',
    flag: 'SOS',
    decimalDigits: 0,
    number: 706,
    namePlural: 'Somali shillings',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'LKR': CurrencyFormatInfo(
    code: 'LKR',
    name: 'Sri Lanka Rupee',
    symbol: '₨',
    flag: 'LKR',
    decimalDigits: 2,
    number: 144,
    namePlural: 'Sri Lankan rupees',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'SRD': CurrencyFormatInfo(
    code: 'SRD',
    name: 'Suriname Dollar',
    symbol: r'$',
    flag: 'SRD',
    decimalDigits: 2,
    number: 968,
    namePlural: 'Suriname Dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'SYP': CurrencyFormatInfo(
    code: 'SYP',
    name: 'Syrian Lira',
    symbol: 'LS',
    flag: 'SYP',
    decimalDigits: 2,
    number: 760,
    namePlural: 'Syrian lira',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: false,
  ),
  'TZS': CurrencyFormatInfo(
    code: 'TZS',
    name: 'Tanzanian Shilling',
    symbol: 'TSh',
    flag: 'TZS',
    decimalDigits: 0,
    number: 834,
    namePlural: 'Tanzanian shillings',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'TTD': CurrencyFormatInfo(
    code: 'TTD',
    name: 'Trinidad and Tobago Dollar',
    symbol: r'TT$',
    flag: 'TTD',
    decimalDigits: 2,
    number: 780,
    namePlural: 'Trinidad and Tobago dollars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'TND': CurrencyFormatInfo(
    code: 'TND',
    name: 'Tunisian dinar',
    symbol: 'د.ت',
    flag: 'TN',
    decimalDigits: 3,
    number: 788,
    namePlural: 'Tunisian dinars',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'UGX': CurrencyFormatInfo(
    code: 'UGX',
    name: 'Ugandan Shilling',
    symbol: 'USh',
    flag: 'UGX',
    decimalDigits: 0,
    number: 800,
    namePlural: 'Ugandan shillings',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'UAH': CurrencyFormatInfo(
    code: 'UAH',
    name: 'Ukraine Hryvnia',
    symbol: '₴',
    flag: 'UAH',
    decimalDigits: 2,
    number: 980,
    namePlural: 'Ukrainian hryvnias',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: false,
  ),
  'UYU': CurrencyFormatInfo(
    code: 'UYU',
    name: 'Uruguay Peso',
    symbol: r'$U',
    flag: 'UYU',
    decimalDigits: 2,
    number: 858,
    namePlural: 'Uruguayan pesos',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'VEF': CurrencyFormatInfo(
    code: 'VEF',
    name: 'Venezuela Bolívar',
    symbol: 'Bs',
    flag: 'VEF',
    decimalDigits: 2,
    number: 937,
    namePlural: 'Venezuelan bolívars',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'VND': CurrencyFormatInfo(
    code: 'VND',
    name: 'Viet Nam Dong',
    symbol: '₫',
    flag: 'VND',
    decimalDigits: 0,
    number: 704,
    namePlural: 'Vietnamese dong',
    thousandsSeparator: '.',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: false,
  ),
  'YER': CurrencyFormatInfo(
    code: 'YER',
    name: 'Yemen Rial',
    symbol: '﷼',
    flag: 'YER',
    decimalDigits: 0,
    number: 886,
    namePlural: 'Yemeni rials',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
  'ZMW': CurrencyFormatInfo(
    code: 'ZMW',
    name: 'Zambian kwacha',
    symbol: 'ZK',
    flag: 'ZM',
    decimalDigits: 2,
    number: 967,
    namePlural: 'Zambian kwachas',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'ZWL': CurrencyFormatInfo(
    code: 'ZWL',
    name: 'Zimbabwean Dollar',
    symbol: r'$ZWL',
    flag: 'ZW',
    decimalDigits: 2,
    number: 932,
    namePlural: 'Zimbabwean dollars',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    spaceBetweenAmountAndSymbol: false,
    symbolOnLeft: true,
  ),
  'IQD': CurrencyFormatInfo(
    code: 'IQD',
    name: 'Iraqi Dinar',
    symbol: 'د.ع',
    flag: 'IQD',
    decimalDigits: 3,
    number: 368,
    namePlural: 'Iraqi dinars',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    spaceBetweenAmountAndSymbol: true,
    symbolOnLeft: true,
  ),
};
